// scaffold/src/js/survey-submit.js — wires the static survey form on the
// thank-you page to HubSpot's Forms Submissions API. Carries the email
// captured upstream via URL parameter (?email=...), reveals the "Other"
// overflow text input when a paired primary field selects an "Other"
// value, collects all field values (including overflow), and POSTs to
// the Submissions API. Flips the per-project survey_completed property
// to true on success.
//
// Generated by hs-lander scaffold. Tokens substituted at build time:
//   __PORTAL_ID__       — HubSpot portal ID
//   __SURVEY_FORM_ID__  — Terraform-defined survey form ID
//   __PROJECT_SLUG__    — project slug; used for the survey_completed property name
//
// Wiring contract (thank-you template):
// - The static <form> carries data-survey-form
// - Overflow text inputs carry data-other-overflow-for="<primary-field-name>"
// - The script tag is loaded with `defer` before {{ standard_footer_includes }}
//
// Submissions API endpoint requires no auth; the form ID is the implicit
// authorisation. See references/forms-submissions-api.md for the rationale
// behind static-form-plus-Submissions-API vs hbspt.forms.create.

(function () {
  var PORTAL_ID = "__PORTAL_ID__";
  var SURVEY_FORM_ID = "__SURVEY_FORM_ID__";
  var SURVEY_COMPLETED_PROPERTY = "__PROJECT_SLUG___survey_completed";

  function getEmailFromURL() {
    var params = new URLSearchParams(window.location.search);
    return params.get("email") || "";
  }

  function isOtherValue(value) {
    return /^other(\s|\(|$)/i.test(String(value || "").trim());
  }

  function collectFields(form) {
    var fields = [];
    var seen = {};

    // Single-value inputs: select, checked radios, single text inputs (skip overflow inputs at this stage).
    var singleSel = form.querySelectorAll("select, input[type='radio']:checked, input[type='text']");
    Array.prototype.forEach.call(singleSel, function (el) {
      if (!el.name || seen[el.name]) return;
      if (el.dataset && el.dataset.otherOverflowFor) return;
      fields.push({ name: el.name, value: el.value });
      seen[el.name] = true;
    });

    // Multi-checkbox values — semicolon-joined per HubSpot's multi-select convention.
    var checkboxNames = {};
    Array.prototype.forEach.call(form.querySelectorAll("input[type='checkbox']:checked"), function (el) {
      if (el.name) checkboxNames[el.name] = true;
    });
    Object.keys(checkboxNames).forEach(function (name) {
      var checked = form.querySelectorAll("input[type='checkbox'][name='" + name + "']:checked");
      var values = Array.prototype.map.call(checked, function (el) { return el.value; });
      fields.push({ name: name, value: values.join(";") });
    });

    // "Other" overflow text inputs — included only when the paired primary
    // field's selected value is "Other" (case-insensitive prefix match).
    Array.prototype.forEach.call(form.querySelectorAll("[data-other-overflow-for]"), function (overflowEl) {
      var primaryName = overflowEl.dataset.otherOverflowFor;
      var primary = fields.filter(function (f) { return f.name === primaryName; })[0];
      if (primary && isOtherValue(primary.value) && (overflowEl.value || "").trim()) {
        fields.push({ name: primaryName + "_other", value: overflowEl.value.trim() });
      }
    });

    return fields;
  }

  // Reveal/hide "Other" overflow inputs as the paired primary field changes.
  function bindOverflowReveal(form) {
    Array.prototype.forEach.call(form.querySelectorAll("[data-other-overflow-for]"), function (overflowEl) {
      var primaryName = overflowEl.dataset.otherOverflowFor;
      var primaryEls = form.querySelectorAll("[name='" + primaryName + "']");
      var update = function () {
        var primaryValue = "";
        var select = form.querySelector("select[name='" + primaryName + "']");
        if (select) {
          primaryValue = select.value;
        } else {
          var radio = form.querySelector("input[type='radio'][name='" + primaryName + "']:checked");
          if (radio) primaryValue = radio.value;
        }
        overflowEl.hidden = !isOtherValue(primaryValue);
      };
      Array.prototype.forEach.call(primaryEls, function (el) {
        el.addEventListener("change", update);
      });
      update();
    });
  }

  function submitSurvey(form, event) {
    event.preventDefault();

    var email = getEmailFromURL();
    if (!email) {
      console.error("survey-submit: no ?email= URL parameter; cannot attribute submission");
      // TODO: surface an inline error UI rather than just console.
      return;
    }

    var fields = [{ name: "email", value: email }]
      .concat(collectFields(form))
      .concat([{ name: SURVEY_COMPLETED_PROPERTY, value: "true" }]);

    var payload = {
      submittedAt: Date.now(),
      fields: fields,
      context: {
        pageUri: location.href,
        pageName: document.title
      }
    };

    var endpoint = "https://api.hsforms.com/submissions/v3/integration/secure/submit/" +
      PORTAL_ID + "/" + SURVEY_FORM_ID;

    fetch(endpoint, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload)
    })
      .then(function (response) {
        if (!response.ok) throw new Error("HTTP " + response.status);
        // Switch the form to its is-submitted state; scaffold CSS handles styling.
        form.classList.add("is-submitted");
      })
      .catch(function (err) {
        console.error("survey-submit: failed", err);
        // TODO: inline error UI.
      });
  }

  document.addEventListener("DOMContentLoaded", function () {
    var form = document.querySelector("[data-survey-form]");
    if (!form) return;
    bindOverflowReveal(form);
    form.addEventListener("submit", function (e) { submitSurvey(form, e); });
  });
})();
